[package]
name = "shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "shell"
path = "src/shell.rs"

[dependencies]
signal-hook = "0.3.13"
