[package]
name = "it_labs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.2"
num-traits = "0.2.14"
rand = "0.8.4"
num = "0.4.0"
gcd = "2.0.2"