[workspace]

members = [
    "arithemtic-evaluator",
    "template-engine",
    "image-cli",
    "rstat",
    "text-viewer",
    "shell",
    "concurrency",
    "linuxio",
    "network",
    "proxy"
#    "test-review",
]